### ISSUE TITLE
What's the difference between @Transformer and the BeanUtils.copyProperties

### ISSUE THREAD

**Issue by Accright** [lotabout/transformer-playground#2]
I have cloned the source code and compiled it successfully. However, when I wanted to run the test case, it showed the error that called "java: Compilation failed: internal java compiler error". Which is the reason that caused this issue?BTW, what's difference between the annotation and the BeanUtils.copyProperties.Is the the main effect generating the  Transformer code automatically?
Thanks a lot.

**Comment by lotabout** [comment]
@Accright 
- How do you run the test cases(`mvn test`)? 
- Which Java version do you use? was tested under JDK 1.8

> what's difference between the annotation and the BeanUtils.copyProperties

This tools would statically generates transformers while `BeanUtils` uses reflections. And one of the concerns of `BeanUtils` is that you have no idea how it get things done. What if two objects are similar but different in some fields(e.g. type or field name)? `@Transformer` would give compile error. Note that [MapStruct](https://mapstruct.org/) might be a better alternative to `@Transformer`.

**Comment by Accright** [comment]
Thanks a lot. The issue has been resolved by replacing java version.
